version: '3'

services:

  datadog:
    image: datadog/agent
    environment:
      - DD_API_KEY=98033318c42383b0240188ec9529d7fb
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  posts-service:
    container_name: "posts-service"
    image: ghcr.io/agustinvon/jibberjabberpost-dev:latest
    ports:
      - "8080:8081"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: jibberjabber-db
      DB_HOST: posts-db-service
      DB_PORT: 5432
      KEYCLOAK_HOST: keycloak-service
      KEYCLOAK_PORT: 8080
      ADMIN_USERNAME: super-admin
      ADMIN_PASSWORD: admin
      FOLLOWERS_HOST: followers-service
      FOLLOWERS_PORT: 8083
    depends_on:
      - posts-db-service
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "posts-service", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'


  followers-service:
    container_name: "followers-service"
    image: ghcr.io/agustinvon/jibberjabberfollowers-dev:latest
    ports:
      - "8083:8083"
     # - "5005:5005"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: jibberjabber-db
      DB_HOST: followers-db-service
      DB_PORT: 5432
      KEYCLOAK_HOST: keycloak-service
      KEYCLOAK_PORT: 8080
    depends_on:
      - followers-db-service
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "followers-service", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

    
  keycloak-service:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak-service
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=jibberjabber.rellum.com.ar
      - KC_HOSTNAME_ADMIN=jibberjabber.rellum.com.ar
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db-service
      - KC_DB_URL_DATABASE=pgdb
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=password
    ports:
      - "8081:8080"
    command: start-dev
    depends_on:
      - keycloak-db-service
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
  
  posts-db-service:
    container_name: "posts-db-service"
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibberjabber-db

  followers-db-service:
    container_name: "followers-db-service"
    image: postgres:12
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibberjabber-db

  keycloak-db-service:
    container_name: "keycloak-db-service"
  
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgdb


  #proxy:
  #  container_name: "jibber-jabber-reverse-proxy"
  #  image: nginx
  #  ports:
  #    - 80:80
  #  volumes:
  #    - ./static/:/usr/share/nginx/html:ro
  #    - ./conf.d:/etc/nginx/conf.d:ro

  ui:
    container_name: ui
    image: ghcr.io/germanbuchmuller/jibber-jabber-base-ui-prod:latest
    ports:
      - 9090:80
    restart: always

  proxy:
    container_name: proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  