version: '3'

services:

  posts-service:
    container_name: "posts-service"
    image: ghcr.io/agustinvon/jibberjabberpost-dev:latest
    ports:
      - "8080:8081"
      - "5005:5005"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: jibberjabber-db
      DB_HOST: posts-db-service
      DB_PORT: 5432
      KEYCLOAK_HOST: keycloak-service
      KEYCLOAK_PORT: 8080
    depends_on:
      - posts-db-service
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 -Djava.security.egd=file:/dev/./urandom  -jar /home/gradle/src/build/libs/JibberJabber-0.0.1-SNAPSHOT.jar
   
  