version: '3'

services:
    
  keycloak-service:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak-service
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db-service
      - KC_DB_URL_DATABASE=pgdb
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=password
    ports:
      - "8081:8080"
    command: start-dev
    depends_on:
      - keycloak-db-service
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
  
  posts-db-service:
    container_name: "posts-db-service"
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibberjabber-db

  followers-db-service:
    container_name: "followers-db-service"
    image: postgres:12
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibberjabber-db

  keycloak-db-service:
    container_name: "keycloak-db-service"
  
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgdb

  proxy:
    container_name: "jibber-jabber-reverse-proxy"
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./static/:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
  